# Generated by Django 3.2.5 on 2021-07-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_email_verified',
        ),
    ]
